<?php include 'header.phtml';?>
<style>
.row{margin-bottom: 1rem;}
</style>
<div class="container">
<h1>只言片语</h1>
<div class="row">
<div class="col-md-2 col-md-offset-2">
  <a type="button" class="btn btn-primary" data-toggle="modal" data-target="#createModal">创建</a></div>
</div>
<?php $roomNum = count($this->roomList);
$rowNum = ceil($roomNum/4);
$offset = 0;
for ($i = 0;$i < $rowNum;$i++) {
  $rooms = array_slice($this->roomList,$offset,4);
  $offset += 4;
?>
<div class="row">
  <?php foreach ($rooms as $key => $room) {?>
    <div class="col-md-3">
      <div class="card card-block">
       <h3 class="card-title"><?=$room['name']?> (<?=$room['user_count']?>)</h3>
       <p class="card-text"><?php if(!$room['password']):?>不<?php endif;?>需要密码</p>
       <a ref="javascript:void(0)" class="btn btn-primary">加入</a>
     </div>
    </div>
    <?php }?>
</div>
<?php }?>


<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">创建房间</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">名称:</label>
            <input type="text" class="form-control" id="room_name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">密码:</label>
            <input type="password" class="form-control" id="room_password">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" id="create_room_btn" class="btn btn-primary">确定</button>
      </div>
    </div>
  </div>
</div>
</div>
<?php include 'footer.phtml';?>
