<?php include 'header.phtml';?>
<style>
.row{margin-bottom: 1rem;}
</style>
<div class="container">
<h1>只言片语</h1>
<div class="row">
<div class="col-md-2 col-md-offset-2"><a type="button" class="btn btn-primary" id="create_room_btn">创建</a></div>
</div>
<?php $roomNum = count($this->roomList);
$rowNum = $roomNum%4;
$offset = 0;
for ($i = 0;$i < $rowNum;$i++) {
  $rooms = array_slice($this->roomList,$offset,4);
  $offset += 4;
?>
<div class="row">
  <?php foreach ($rooms as $key => $room) {?>
    <div class="col-md-3">
      <div class="card card-block">
       <h3 class="card-title"><?=$room['name']?> (<?=$room['user_count']?>)</h3>
       <p class="card-text">房间描述</p>
       <a ref="javascript:void(0)" class="btn btn-primary">加入</a>
     </div>
    </div>
    <?php }?>
</div>
<?php }?>
</div>
<?php include 'footer.phtml';?>
