<?php include 'header.phtml';?>
<style>
.row{margin-bottom: 1rem;}
</style>
<div class="container">
  <h1><?=$this->room['name']?></h1>

  <div class="row">
    <div class="col-md-2">
      <p><?=$this->uid?></p>
    </div>
    <div class="col-md-2">
    <?php if($this->isJoined):?>
      <a type="button" id="quit-btn" data-id="<?=$this->room['id']?>" class="btn btn-danger">退出</a>
    <?php else:?>
      <a type="button" id="join-btn" data-id="<?=$this->room['id']?>" class="btn btn-info">加入</a>
    <?php endif;?>
    </div>
  </div>

  <p> 用户列表： </p>
  <div id="user_list">
  </div>
  <?php if($this->room['creator'] == $this->uid):?>
  <div id="start_ui"><a id="start_btn" class="btn btn-danger">开始游戏</a></div>
  <?php endif;?>
  <div id="my_cards" class="row">
    <div></div>
  </div>
  <div id="keyword_ui" class="row" style="display:none">
    <div class="col-md-2"><input type="text" class="form-control" id="keyword_input"></div>
    <div class="col-md-2"><a class="btn btn-primary" href="javascript:void(0)" id="keyword_btn">确定</a></div>
  </div>
</div>
<script>
var uid = "<?=$this->uid?>"
var selected_my_card = 0;
var ws = new WebSocket('ws://<?=$this->wsHost?>/?uid='+uid+'&room_id=<?=$this->room['id']?>');
</script>
<?php include 'footer.phtml';?>
